path.root <- "/Users/davgutavi/NAS_PROYECTOS/iot_smart_agent/NEUROCOMPUTING/datasets/simulados_original"

path.alhaurin           <- paste0(path.root,"/alhaurindelatorre")
path.antequera          <- paste0(path.root,"/antequera")
path.benalmadena        <- paste0(path.root,"/benalmadena")
path.estepona           <- paste0(path.root,"/estepona")
path.fuengirola         <- paste0(path.root,"/fuengirola")
path.malaga             <- paste0(path.root,"/malaga")
path.mijas              <- paste0(path.root,"/mijas")
path.nerja              <- paste0(path.root,"/nerja")
path.rincondelavictoria <- paste0(path.root,"/rincondelavictoria")
path.ronda              <- paste0(path.root,"/ronda")
path.torremolinos       <- paste0(path.root,"/torremolinos")
path.velezmalaga        <- paste0(path.root,"/velezmalaga")

path.alhaurin.pressure      <- paste0(path.alhaurin,"/atmosphericPressure.csv")
path.alhaurin.precipitation <- paste0(path.alhaurin,"/precipitation.csv")
path.alhaurin.humidity      <- paste0(path.alhaurin,"/relativeHumidity.csv")
path.alhaurin.radiation     <- paste0(path.alhaurin,"/solarRadiation.csv")
path.alhaurin.temperature   <- paste0(path.alhaurin,"/temperature.csv")
path.alhaurin.direction     <- paste0(path.alhaurin,"/windDirection.csv")
path.alhaurin.speed         <- paste0(path.alhaurin,"/windSpeed.csv")

path.antequera.pressure      <- paste0(path.antequera,"/atmosphericPressure.csv")
path.antequera.precipitation <- paste0(path.antequera,"/precipitation.csv")
path.antequera.humidity      <- paste0(path.antequera,"/relativeHumidity.csv")
path.antequera.radiation     <- paste0(path.antequera,"/solarRadiation.csv")
path.antequera.temperature   <- paste0(path.antequera,"/temperature.csv")
path.antequera.direction     <- paste0(path.antequera,"/windDirection.csv")
path.antequera.speed         <- paste0(path.antequera,"/windSpeed.csv")

path.benalmadena.pressure      <- paste0(path.benalmadena,"/atmosphericPressure.csv")
path.benalmadena.precipitation <- paste0(path.benalmadena,"/precipitation.csv")
path.benalmadena.humidity      <- paste0(path.benalmadena,"/relativeHumidity.csv")
path.benalmadena.radiation     <- paste0(path.benalmadena,"/solarRadiation.csv")
path.benalmadena.temperature   <- paste0(path.benalmadena,"/temperature.csv")
path.benalmadena.direction     <- paste0(path.benalmadena,"/windDirection.csv")
path.benalmadena.speed         <- paste0(path.benalmadena,"/windSpeed.csv")
#
path.estepona.pressure      <- paste0(path.estepona,"/atmosphericPressure.csv")
path.estepona.precipitation <- paste0(path.estepona,"/precipitation.csv")
path.estepona.humidity      <- paste0(path.estepona,"/relativeHumidity.csv")
path.estepona.radiation     <- paste0(path.estepona,"/solarRadiation.csv")
path.estepona.temperature   <- paste0(path.estepona,"/temperature.csv")
path.estepona.direction     <- paste0(path.estepona,"/windDirection.csv")
path.estepona.speed         <- paste0(path.estepona,"/windSpeed.csv")

path.fuengirola.pressure      <- paste0(path.fuengirola,"/atmosphericPressure.csv")
path.fuengirola.precipitation <- paste0(path.fuengirola,"/precipitation.csv")
path.fuengirola.humidity      <- paste0(path.fuengirola,"/relativeHumidity.csv")
path.fuengirola.radiation     <- paste0(path.fuengirola,"/solarRadiation.csv")
path.fuengirola.temperature   <- paste0(path.fuengirola,"/temperature.csv")
path.fuengirola.direction     <- paste0(path.fuengirola,"/windDirection.csv")
path.fuengirola.speed         <- paste0(path.fuengirola,"/windSpeed.csv")

path.malaga.pressure      <- paste0(path.malaga,"/atmosphericPressure.csv")
path.malaga.precipitation <- paste0(path.malaga,"/precipitation.csv")
path.malaga.humidity      <- paste0(path.malaga,"/relativeHumidity.csv")
path.malaga.radiation     <- paste0(path.malaga,"/solarRadiation.csv")
path.malaga.temperature   <- paste0(path.malaga,"/temperature.csv")
path.malaga.direction     <- paste0(path.malaga,"/windDirection.csv")
path.malaga.speed         <- paste0(path.malaga,"/windSpeed.csv")

path.mijas.pressure      <- paste0(path.mijas,"/atmosphericPressure.csv")
path.mijas.precipitation <- paste0(path.mijas,"/precipitation.csv")
path.mijas.humidity      <- paste0(path.mijas,"/relativeHumidity.csv")
path.mijas.radiation     <- paste0(path.mijas,"/solarRadiation.csv")
path.mijas.temperature   <- paste0(path.mijas,"/temperature.csv")
path.mijas.direction     <- paste0(path.mijas,"/windDirection.csv")
path.mijas.speed         <- paste0(path.mijas,"/windSpeed.csv")

path.nerja.pressure      <- paste0(path.nerja,"/atmosphericPressure.csv")
path.nerja.precipitation <- paste0(path.nerja,"/precipitation.csv")
path.nerja.humidity      <- paste0(path.nerja,"/relativeHumidity.csv")
path.nerja.radiation     <- paste0(path.nerja,"/solarRadiation.csv")
path.nerja.temperature   <- paste0(path.nerja,"/temperature.csv")
path.nerja.direction     <- paste0(path.nerja,"/windDirection.csv")
path.nerja.speed         <- paste0(path.nerja,"/windSpeed.csv")

path.rincondelavictoria.pressure      <- paste0(path.rincondelavictoria,"/atmosphericPressure.csv")
path.rincondelavictoria.precipitation <- paste0(path.rincondelavictoria,"/precipitation.csv")
path.rincondelavictoria.humidity      <- paste0(path.rincondelavictoria,"/relativeHumidity.csv")
path.rincondelavictoria.radiation     <- paste0(path.rincondelavictoria,"/solarRadiation.csv")
path.rincondelavictoria.temperature   <- paste0(path.rincondelavictoria,"/temperature.csv")
path.rincondelavictoria.direction     <- paste0(path.rincondelavictoria,"/windDirection.csv")
path.rincondelavictoria.speed         <- paste0(path.rincondelavictoria,"/windSpeed.csv")

path.ronda.pressure      <- paste0(path.ronda,"/atmosphericPressure.csv")
path.ronda.precipitation <- paste0(path.ronda,"/precipitation.csv")
path.ronda.humidity      <- paste0(path.ronda,"/relativeHumidity.csv")
path.ronda.radiation     <- paste0(path.ronda,"/solarRadiation.csv")
path.ronda.temperature   <- paste0(path.ronda,"/temperature.csv")
path.ronda.direction     <- paste0(path.ronda,"/windDirection.csv")
path.ronda.speed         <- paste0(path.ronda,"/windSpeed.csv")

path.torremolinos.pressure      <- paste0(path.torremolinos,"/atmosphericPressure.csv")
path.torremolinos.precipitation <- paste0(path.torremolinos,"/precipitation.csv")
path.torremolinos.humidity      <- paste0(path.torremolinos,"/relativeHumidity.csv")
path.torremolinos.radiation     <- paste0(path.torremolinos,"/solarRadiation.csv")
path.torremolinos.temperature   <- paste0(path.torremolinos,"/temperature.csv")
path.torremolinos.direction     <- paste0(path.torremolinos,"/windDirection.csv")
path.torremolinos.speed         <- paste0(path.torremolinos,"/windSpeed.csv")

path.velezmalaga.pressure      <- paste0(path.velezmalaga,"/atmosphericPressure.csv")
path.velezmalaga.precipitation <- paste0(path.velezmalaga,"/precipitation.csv")
path.velezmalaga.humidity      <- paste0(path.velezmalaga,"/relativeHumidity.csv")
path.velezmalaga.radiation     <- paste0(path.velezmalaga,"/solarRadiation.csv")
path.velezmalaga.temperature   <- paste0(path.velezmalaga,"/temperature.csv")
path.velezmalaga.direction     <- paste0(path.velezmalaga,"/windDirection.csv")
path.velezmalaga.speed         <- paste0(path.velezmalaga,"/windSpeed.csv")